
install.packages("binom")
install.packages("BSDA")
install.packages("car")
install.packages("dplyr")
install.packages("dunn.test")
install.packages("EnvStats")
install.packages("epiR")
install.packages("FSA")
install.packages("lawstat")
install.packages("lsr")
install.packages("moments")
install.packages("nortest")
install.packages("openxlsx")
install.packages("rcompanion")
install.packages("readxl")
install.packages("robustbase")
install.packages("stringi")
